import type { BookConfig } from "@/types/book";

export const filhosPrussiaConfig: BookConfig = {
  id: "filhos-prussia",
  slug: "filhos-prussia",
  title: "Filhos da Prússia",
  subtitle: "Você foi construído. Não educado.",
  category: "Filosofia Social · Educação",
  hook: "Você não saiu da escola.\nA escola ficou em você.",
  territory: [
    "Desde a infância, fomos ensinados a sentar, repetir, aceitar e competir. Não porque isso nos tornasse livres. Mas porque isso nos tornava gerenciáveis.",
    "Este livro investiga as raízes psicológicas, históricas e sociais do modelo educacional que moldou gerações para obedecer antes de questionar. Não como vitimismo. Como anatomia.",
    "Entender a estrutura não te liberta automaticamente. Mas torna impossível não ver.",
  ],
  questions: [
    "Quem projetou o sistema que você chama de educação — e com que objetivo?",
    "Quais comportamentos seus são escolhas — e quais são obediência disfarçada?",
    "O que teria sido diferente se você tivesse sido educado em vez de construído?",
  ],
  leadTeaser: "Entenda a estrutura antes de decidir o que fazer com ela.",
  amazonUrl: "https://www.amazon.com.br/FILHOS-PR%C3%9ASSIA-Voc%C3%AA-constru%C3%ADdo-educado-ebook/dp/B0GWSKJK92",
  amazonPrice: "R$ 9,99",
  amazonPricePrint: "Consulte na página da obra",
  coverImage: "/images/filho_da_prussia.jpg",
  mindMapImage: "",
  audioEmbedUrl: "",
  emailWebhookUrl: "https://SEU_WEBHOOK_AQUI/filhos-prussia",
  theme: {
    bg: "#0A0A0A",
    surface: "#121211",
    primary: "#D4C1A1",
    secondary: "#4A4A46",
    accent: "#A9824C",
    text: "#ECE7DD",
    fontTitle: "Playfair+Display:wght@700;800",
    fontBody: "Spectral:wght@400;500",
    fontAccent: "IBM+Plex+Sans+Condensed:wght@400;600",
  },
  archetype: "O Rebelde Observador",
  temperature: "Pressão silenciosa institucional",
  feeling: ["opressiva", "rígida", "hipnótica"],
  motionProfile: "subterraneo",
  seoDescription: "Filhos da Prússia — você foi construído, não educado. Anatomia do condicionamento, Casa Bonaparte.",
  ogImage: "/images/filho_da_prussia.jpg",
  audioDurationLabel: "40 minutos",
};
