import type { BookConfig } from "@/types/book";

export const deusNaoSeparaConfig: BookConfig = {
  id: "deus-nao-separa",
  slug: "deus-nao-separa",
  title: "O Deus Que Não Se Separa",
  subtitle: "Cristo Antes da Igreja",
  category: "Espiritualidade · Filosofia",
  hook: "Se Deus é absoluto,\nEle não se separa.\nNada está fora da Fonte.",
  territory: [
    "Este não é um livro contra Deus. É um livro contra o medo que foi instalado em nome de Deus.",
    "Criado dentro de um dualismo que dividia o mundo entre salvos e perdidos, Abnadaby Bonaparte atravessa neste livro uma reconstrução espiritual radical — não para abandonar Cristo, mas para perguntar se a separação que aprendemos a chamar de fé realmente pertence a Deus.",
    "Nada está fora da Fonte. Tudo está sendo reintegrado.",
  ],
  questions: [
    "O que sobra da espiritualidade quando o medo é retirado da equação?",
    "Cristo e a Igreja são a mesma coisa — ou uma instituiu o que a outra nunca disse?",
    "Pode existir fé sem divisão entre salvos e perdidos?",
  ],
  leadTeaser: "Uma travessia espiritual que começa onde o dogma termina.",
  amazonUrl: "https://www.amazon.com.br/Deus-Que-N%C3%A3o-Se-Separa-ebook/dp/B0GZNQQH3K",
  amazonPrice: "R$ 9,99",
  amazonPricePrint: "Consulte na página da obra",
  coverImage: "/images/O_DEUS_QUE_NAO_SE_SEPARA.jpg",
  heroImage: "/images/library.jpg",
  mindMapImage: "",
  audioEmbedUrl: "",
  emailWebhookUrl: "https://SEU_WEBHOOK_AQUI/deus-nao-separa",
  theme: {
    bg: "#080A0C",
    surface: "#0d1118",
    primary: "#E0B46A",
    secondary: "#6B5845",
    accent: "#FFF1D0",
    text: "#F5EBDD",
    fontTitle: "Cormorant+SC:wght@600;700",
    fontBody: "EB+Garamond:wght@400;500",
    fontAccent: "Raleway:wght@300;400",
  },
  archetype: "O Místico Integrador",
  temperature: "Transcendência contemplativa oceânica",
  feeling: ["infinita", "serena", "cósmica"],
  motionProfile: "contemplativo",
  seoDescription: "O Deus Que Não Se Separa — Cristo antes da Igreja. Reintegração metafísica, Casa Bonaparte.",
  ogImage: "/images/O_DEUS_QUE_NAO_SE_SEPARA.jpg",
  audioDurationLabel: "45 minutos",
};
