import type { BookConfig } from "@/types/book";

export const burnoutConfig: BookConfig = {
  id: "burnout",
  slug: "burnout",
  title: "Cura Natural para Burnout",
  subtitle: "Como reconstruí minha saúde quando a mente já tinha desistido",
  category: "Saúde · Bem-estar",
  hook: "Você não está fraco.\nVocê está desregulado.\nBurnout não é falta de força.\nÉ o corpo cobrando uma conta ignorada por tempo demais.",
  territory: [
    "Abnadaby Bonaparte escreveu este livro com o corpo ainda doendo. Não de uma cadeira de escritório. De dentro de um rancho no Tocantins, depois de um colapso silencioso que durou meses sem ter nome.",
    "Sem fórmulas mágicas. Sem promessas vazias. Apenas o protocolo real — sono, movimento, alimentação, silêncio, propósito — que ajudou a reconstruir energia, clareza mental e estabilidade emocional.",
    "Reconstrução prática. Baseada em experiência real. Para quem já tentou tudo e está cansado de estar cansado.",
  ],
  questions: [
    "Como você sabe quando o cansaço que sente não é preguiça — é colapso?",
    "Existe um protocolo real de recuperação — ou cada corpo encontra o próprio caminho?",
    "O que muda quando você para de tentar funcionar e começa a se reconstruir?",
  ],
  leadTeaser: "Veja o protocolo antes de decidir se faz sentido para você.",
  amazonUrl: "https://www.amazon.com.br/Cura-Natural-Burnout-Estresse-Exaust%C3%A3o-ebook/dp/B0GWSCKZCC",
  amazonPrice: "R$ 9,99",
  amazonPricePrint: "Consulte na página da obra",
  coverImage: "/images/burnout.png",
  mindMapImage: "",
  audioEmbedUrl: "",
  emailWebhookUrl: "https://SEU_WEBHOOK_AQUI/burnout",
  theme: {
    bg: "#1A120D",
    surface: "#221910",
    primary: "#D89A52",
    secondary: "#7B4F2E",
    accent: "#F5D4A5",
    text: "#F3E6D2",
    fontTitle: "Merriweather:wght@700;900",
    fontBody: "Source+Serif+4:wght@400;500",
    fontAccent: "Nunito:wght@300;400",
  },
  archetype: "O Curador Ferido",
  temperature: "Calor terapêutico reconstrutivo",
  feeling: ["orgânica", "humana", "reconstrutiva"],
  motionProfile: "organico",
  seoDescription: "Cura natural para burnout — reconstrução biológica e protocolo vivido, Casa Bonaparte.",
  ogImage: "/images/burnout.png",
  audioDurationLabel: "35 minutos",
};
