import type { BookConfig } from "@/types/book";

export const heimatConfig: BookConfig = {
  id: "heimat",
  slug: "heimat",
  title: "HEIMAT",
  subtitle: "O Animal Ancestral e o Humano Opcional",
  category: "Filosofia · Ancestralidade",
  hook: "Um pinguim abandonou a colônia.\nNão havia explicação.\nApenas gelo.",
  territory: [
    "Existe algo dentro de você que é anterior à linguagem, anterior à cultura, anterior à identidade que você construiu. Esse algo não desaparece. Apenas fica abafado.",
    "HEIMAT atravessa memória, exílio, ancestralidade e consciência para investigar uma pergunta silenciosa: quanto da sua vida é escolha — e quanto é apenas programação instalada antes de você ter nome?",
    "Não é sobre geografia. É sobre o momento em que você para de fugir de si mesmo.",
  ],
  questions: [
    "De onde você veio — e o que isso ainda faz em você?",
    "O que significa pertencer quando você não cabe mais onde estava?",
    "Instinto e consciência podem coexistir — ou um sempre derrota o outro?",
  ],
  leadTeaser: "Receba o mapa desta travessia antes de embarcar.",
  amazonUrl: "https://www.amazon.com.br/HEIMAT-Animal-Ancestral-Humano-Opcional-ebook/dp/B0GWWS17TF",
  amazonPrice: "R$ 9,99",
  amazonPricePrint: "Consulte na página da obra",
  coverImage: "/images/heimat.jpg",
  mindMapImage: "",
  audioEmbedUrl: "",
  emailWebhookUrl: "https://SEU_WEBHOOK_AQUI/heimat",
  theme: {
    bg: "#ECE9E2",
    surface: "#e4e1da",
    primary: "#1F2328",
    secondary: "#6B7075",
    accent: "#B8A48B",
    text: "#111111",
    fontTitle: "EB+Garamond:wght@600;700;800",
    fontBody: "EB+Garamond:wght@400;500",
    fontAccent: "Raleway:wght@300;400",
  },
  archetype: "O Errante Primordial",
  temperature: "Silêncio glacial com tensão ancestral",
  feeling: ["fria", "solitária", "respirável"],
  motionProfile: "glacial",
  seoDescription: "HEIMAT — o animal ancestral e o humano opcional. Filosofia, exílio e ancestralidade, Casa Bonaparte.",
  ogImage: "/images/heimat.jpg",
  audioDurationLabel: "38 minutos",
};
